# Generated by Django 5.2.8 on 2026-01-06 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_reply', '0012_alter_rulecondition_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='cloudinary_api_key',
            field=models.CharField(blank=True, help_text='Your personal Cloudinary API key for independent attachment storage', max_length=255, null=True),
        ),
    ]
