"""
Django settings for gmail_auto_reply project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Load environment variables from .env (if present)
env_path = Path(__file__).resolve().parent.parent / '.env'
try:
    from dotenv import load_dotenv  # type: ignore
    load_dotenv(env_path, override=True)
except Exception as e:
    # Fallback manual parser
    if env_path.exists():
        try:
            for line in env_path.read_text(encoding='utf-8').splitlines():
                line = line.strip()
                if not line or line.startswith('#') or '=' not in line:
                    continue
                k, v = line.split('=', 1)
                os.environ[k.strip()] = v.strip()
        except Exception:
            pass

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/


# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'django-insecure-jit4840ra0av7ksoq!7&5-+viz+n80r3)-&yqfi7=sp$#7j(5e')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'auto_reply',
    'social_django',
    # APScheduler is optional; if installed will enable in-app auto pull
]

# Restrict login/connect to these domains/emails
ALLOWED_EMAIL_DOMAINS = ['@srimatech.com']
ALLOWED_EMAILS = ['pallerlavijay315@gmail.com', 'manipallerla315@gmail.com' ,'vijayypallerla@gmail.com']

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'gmail_auto_reply.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                # Social Auth context processors (for templates using social auth)
                'social_django.context_processors.backends',
                'social_django.context_processors.login_redirect',
            ],
        },
    },
]

WSGI_APPLICATION = 'gmail_auto_reply.wsgi.application'



import dj_database_url
# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
# For local development (SQLite):
import sys
if sys.platform == 'win32':
    LOCALAPPDATA = os.environ.get('LOCALAPPDATA', os.path.expanduser('~'))
    DB_DIR = os.path.join(LOCALAPPDATA, 'GmailAutoReply')
    os.makedirs(DB_DIR, exist_ok=True)
    DB_PATH = os.path.join(DB_DIR, 'db.sqlite3')
else:
    DB_PATH = BASE_DIR / 'db.sqlite3'
DATABASES = {
    'default': dj_database_url.config(
        default=f'sqlite:///{DB_PATH}',
        conn_max_age=600
    )
}
# For production (PostgreSQL via dj-database-url):
# DATABASES = {
#     'default': dj_database_url.config(default=os.environ.get('DATABASE_URL', f'sqlite:///{os.path.join(BASE_DIR, "db.sqlite3")}'))
# }
CELERY_RESULT_SERIALIZER = 'json'

# Social Auth (Google OAuth2)
AUTHENTICATION_BACKENDS = (
    'social_core.backends.google.GoogleOAuth2',
    'django.contrib.auth.backends.ModelBackend',
)
# App Login (profile only) keys are read from environment variables
SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = os.environ.get('SOCIAL_GOOGLE_CLIENT_ID', '')
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = os.environ.get('SOCIAL_GOOGLE_CLIENT_SECRET', '')
# Scopes for login (OpenID) and optionally Gmail modify (kept here if you want unified flow)
# Scopes for login (OpenID) and Gmail access
SOCIAL_AUTH_GOOGLE_OAUTH2_SCOPE = [
    'openid',
    'email',
    'profile',
    'https://www.googleapis.com/auth/gmail.modify',
]

# Always show Google account chooser and request offline access for refresh token
SOCIAL_AUTH_GOOGLE_OAUTH2_AUTH_EXTRA_ARGUMENTS = {
    'access_type': 'offline',
    'prompt': 'consent',
}

# Gmail API OAuth client (used for explicit "Connect Gmail" flow) – loaded for convenience
GMAIL_CLIENT_ID = os.environ.get('GMAIL_CLIENT_ID', '')
GMAIL_CLIENT_SECRET = os.environ.get('GMAIL_CLIENT_SECRET', '')
GMAIL_OAUTH_SCOPES = os.environ.get('GMAIL_OAUTH_SCOPES', 'https://www.googleapis.com/auth/gmail.modify,https://www.googleapis.com/auth/gmail.settings.basic')
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

# Auto-reply duplicate suppression window (in hours)
REPLY_COOLDOWN_HOURS = int(os.environ.get('REPLY_COOLDOWN_HOURS', '24'))

# Interval (seconds) for in-app Gmail auto pull (APScheduler). Default 60.
GMAIL_PULL_INTERVAL_SECONDS = int(os.environ.get('GMAIL_PULL_INTERVAL_SECONDS', '45'))

# Static files (CSS, JavaScript, Images)
STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [BASE_DIR / 'static']
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True




# Media uploads
if sys.platform == 'win32':
    LOCALAPPDATA = os.environ.get('LOCALAPPDATA', os.path.expanduser('~'))
    MEDIA_ROOT = os.path.join(LOCALAPPDATA, 'GmailAutoReply', 'media')
    os.makedirs(MEDIA_ROOT, exist_ok=True)
else:
    MEDIA_ROOT = BASE_DIR / 'media'
MEDIA_URL = '/media/'

# Cloudinary Storage (optional). Set CLOUDINARY_URL env var to enable cloud storage.
if os.environ.get('CLOUDINARY_URL'):
    import cloudinary
    cloudinary.config(url=os.environ.get('CLOUDINARY_URL'))
    # Use Django 4.2+ STORAGES setting instead of deprecated DEFAULT_FILE_STORAGE
    STORAGES = {
        "default": {
            "BACKEND": "auto_reply.cloudinary_storage.CloudinaryStorage",
        },
        "staticfiles": {
            "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
        },
    }
    MEDIA_URL = 'https://res.cloudinary.com/{}/image/upload/'.format(os.environ.get('CLOUDINARY_CLOUD_NAME', ''))
else:
    # Use default file system storage
    STORAGES = {
        "default": {
            "BACKEND": "django.core.files.storage.FileSystemStorage",
        },
        "staticfiles": {
            "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
        },
    }

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Restrict Google login to allowed domain
SOCIAL_AUTH_PIPELINE = (
    'social_core.pipeline.social_auth.social_details',
    'social_core.pipeline.social_auth.social_uid',
    'social_core.pipeline.social_auth.auth_allowed',
    'social_core.pipeline.social_auth.social_user',
    'social_core.pipeline.user.get_username',
    'social_core.pipeline.user.create_user',
    'auto_reply.social_pipeline.restrict_email_domain',  # <--- domain check
    'auto_reply.social_pipeline.save_gmail_token',       # <--- Save Gmail Token
    'social_core.pipeline.social_auth.associate_user',
    'social_core.pipeline.social_auth.load_extra_data',
    'social_core.pipeline.user.user_details',
)

SOCIAL_AUTH_RAISE_EXCEPTIONS = False
